[default]
service_name = "huc-editor-service"
#FastAPI
fastapi_title = "HuC Editor API Service"
fastapi_description = ""


xslt_dir = "@format {env[BASE_DIR]}/resources/xslt"

log_file = "@format {env[BASE_DIR]}/logs/hec.log"
log_level = 10
log_format = "%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s"